name: 'Testing'
on: [push]
jobs:
    Unit-testing:
      runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
          run: npm ci
        - name: Run test
          run: npm run test
