name: 'Testing'
on:
  push:
    branches: ["dev"]
jobs:
    Unit-testing:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Run test
          run: npm run test
